config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do 
    namespace 'v1' do
    
      resources :users, only: [:index] do
        resources :friendships, only: [:index, :create]
      end
    
      resources :posts, only: [:index, :show, :create, :destroy, :update] do 
        resources :comments, only: [:create, :index]
        resources :likes, only: [:create]
      end
      
      resources :comments, only: [:destroy, :show, :update] do
        resources :likes, only: [:create]
      end
    
      resources :likes, only: [:show, :destroy]
      resources :friendships, only: [:show, :update, :destroy]
      resources :notifications, only: [:update]
    end
  end
  
  root 'welcome#app'
  get '/login', to: 'welcome#login'
  get '/signup', to: 'welcome#signup'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users, only: [:index, :show] do
    resources :friendships, only: [:index], path: "friends"
  end
  resources :posts, only: [:show]  
  
  # get 'auth/:provider/callback', to: 'devise/sessions#create'
  # get 'auth/failure', to: redirect('/')

  get '/*path' => 'welcome#app'

  
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likable
  include Notifiable
  
  belongs_to :user
  belongs_to :post
  mount_uploader :picture, PictureUploader

  validates :body, presence: true

  scope :desc, -> { order("created_at DESC") }

  def data
    return {
      type: "comment",
      id: self.id,
      body: self.body,
      created_at: created_at_pst,
      user: {
        id: self.user_id,
        name: self.user.name
      },
      picture: self.picture,
      likes: self.likes
    }
  end

  def created_at_pst
    self.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%b %e, %Y %l:%M %p")
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      before_action :require_login

      def index
        @post = Post.find(params[:post_id])
        @comments = @post.comments_data
        render json: @comments, status: :ok
      end
    
      def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(params.require(:comment).permit(:body, :picture))
        @comment.user_id = current_user.id
        if @comment.save
          @comments = @post.comments_data
          @comment.notify(@post.user, "#{current_user.name} commented on your post") #unless @post.user == current_user
          render json: {success: "commented successfully", post: @post.data, comments: @comments}, status: :ok
        else
          render json: {error: "couldnt comment"}, status: :unprocessable_entity
        end
      end
    
      def destroy
        @comment = Comment.find(params[:id])
        @parent = @comment.post
        if @comment.destroy
          @comments = @parent.comments_data
          render json: { message: "deleted comment", post: @parent.data, comments: @comments, comment: @comment }, status: :ok
        else
          render json: { message: "failed to delete comment"}, status: 422
        end
      end

      def update
        @comment = Comment.find(params[:id])
        @parent = @comment.post
        if @comment.update(body: params[:body])
          @comments = @parent.comments_data
          render json: { message: "edited comment", post: @parent.data, comments: @comments, comment: @comment }, status: :ok
        else
          render json: { message: "failed to edit comment"}, status: 422
        end
      end
    
      def show
        @comment = Comment.find(params[:id])
        redirect_to @comment.post
      end
    end
    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def show
    @comment = Comment.find(params[:id])
    redirect_to @comment.post
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="well col-xs-8">
    <%= image_tag comment.picture.url if comment.picture? %>
    <p><%= comment.body %></p>
    <i><%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at_pst) %> ago </i>
    <span class="label label-success"><%= pluralize(comment.likes.count, "Like")%></span>
    <% if comment.liked_by?(current_user) %>
      <%= link_to 'Unlike', comment_like_path(comment, comment.find_like_from(current_user)), method: :delete, class: "btn btn-xs btn-default"%>
    <% else %>
      <%= link_to 'Like', comment_likes_path(comment), method: :post, class: "btn btn-xs btn-primary"%>
    <% end %>
    <% if current_user == comment.user || comment.user == comment.post.user %>
      <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="well col-xs-8">
  <%= render 'shared/errors', obj: @comment%>
    <%= form_for([@post, @comment], :html => { class: "form", role: "form" }) do |f| %>
      <div class='form-group'>
        <%= f.text_area :body, rows: 2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary btn-large' %>
      </div>
      <span class="picture">
        <%= f.label :picture, 'Upload a photo' %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
      </span>
    <% end %>
  </div>
</div>